"""Agregar columna cargo a solicitudes

Revision ID: 9da0cf36ee40
Revises: 3b8efa0b0b11
Create Date: 2024-11-21 11:05:00.822285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da0cf36ee40'
down_revision = '3b8efa0b0b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('cargo')

    # ### end Alembic commands ###
